// account-ui/src/config/clientRegistry.js
export const CLIENT_CONFIGS = {
  'team3': {
    name: 'team3',
    description: 'Generated by SSO CLI',
    icon: '🆕',
    primaryColor: '#16A34A',
    redirectUrl: 'https://team3.local.test:8789/callback'
  },
  'team2': {
    name: 'team2',
    description: 'Generated by SSO CLI',
    icon: '🆕',
    primaryColor: '#16A34A',
    redirectUrl: 'https://team2.local.test:8987/callback'
  },
  'team1': {
    name: 'team1',
    description: 'Generated by SSO CLI',
    icon: '🆕',
    primaryColor: '#16A34A',
    redirectUrl: 'https://team1.local.test:8797/callback'
  },
  'fixed4org': {
    name: 'fixed4org',
    description: 'Generated by SSO CLI',
    icon: '🆕',
    primaryColor: '#16A34A',
    redirectUrl: 'https://fixed4org.local.test:8888/callback'
  },
  'fixed3org': {
    name: 'fixed3org',
    description: 'Generated by SSO CLI',
    icon: '🆕',
    primaryColor: '#16A34A',
    redirectUrl: 'https://fixed3org.local.test:7877/callback'
  },
  'fixed2': {
    name: 'fixed2',
    description: 'Generated by SSO CLI',
    icon: '🆕',
    primaryColor: '#16A34A',
    redirectUrl: 'https://fixed2.local.test:9899/callback'
  },
  'fixed1': {
    name: 'fixed1',
    description: 'Generated by SSO CLI',
    icon: '🆕',
    primaryColor: '#16A34A',
    redirectUrl: 'https://fixed1.local.test:7888/callback'
  },
  'fixed': {
    name: 'fixed',
    description: 'Generated by SSO CLI',
    icon: '🆕',
    primaryColor: '#16A34A',
    redirectUrl: 'https://fixed.local.test:8777/callback'
  },
  'orgche': {
    name: 'orgche',
    description: 'Generated by SSO CLI',
    icon: '🆕',
    primaryColor: '#16A34A',
    redirectUrl: 'http://orgche.local.test:9899/callback'
  },
  'cheeee': {
    name: 'cheeee',
    description: 'Generated by SSO CLI',
    icon: '🆕',
    primaryColor: '#16A34A',
    redirectUrl: 'http://cheeee.local.test:7876/callback'
  },
  'demooo4': {
    name: 'demooo4',
    description: 'Generated by SSO CLI',
    icon: '🆕',
    primaryColor: '#16A34A',
    redirectUrl: 'http://demooo4.local.test:5678/callback'
  },
  'demooo3': {
    name: 'demooo3',
    description: 'Generated by SSO CLI',
    icon: '🆕',
    primaryColor: '#16A34A',
    redirectUrl: 'http://demooo3.local.test:7789/callback'
  },
  'demoo2': {
    name: 'demoo2',
    description: 'Generated by SSO CLI',
    icon: '🆕',
    primaryColor: '#16A34A',
    redirectUrl: 'http://demoo2.local.test:7777/callback'
  },
  'demooo': {
    name: 'demooo',
    description: 'Generated by SSO CLI',
    icon: '🆕',
    primaryColor: '#16A34A',
    redirectUrl: 'http://demooo.local.test:7878/callback'
  },
  'sss2': {
    name: 'sss2',
    description: 'Generated by SSO CLI',
    icon: '🆕',
    primaryColor: '#16A34A',
    redirectUrl: 'http://sss2.local.test:7777/callback'
  },
  'sss1': {
    name: 'sss1',
    description: 'Generated by SSO CLI',
    icon: '🆕',
    primaryColor: '#16A34A',
    redirectUrl: 'http://sss1.local.test:6787/callback'
  },
  'sss': {
    name: 'sss',
    description: 'Generated by SSO CLI',
    icon: '🆕',
    primaryColor: '#16A34A',
    redirectUrl: 'http://sss.local.test:8787/callback'
  },
  'vite': {
    name: 'vite',
    description: 'Generated by SSO CLI',
    icon: '🆕',
    primaryColor: '#16A34A',
    redirectUrl: 'http://localhost:5173/callback'
  },
  'logout1': {
    name: 'logout1',
    description: 'Generated by SSO CLI',
    icon: '🆕',
    primaryColor: '#16A34A',
    redirectUrl: 'http://localhost:5173/callback'
  },
  'logout': {
    name: 'logout',
    description: 'Generated by SSO CLI',
    icon: '🆕',
    primaryColor: '#16A34A',
    redirectUrl: 'http://localhost:5173/callback'
  },
  'any1': {
    name: 'any1',
    description: 'Generated by SSO CLI',
    icon: '🆕',
    primaryColor: '#16A34A',
    redirectUrl: 'http://localhost:5173/callback'
  },
  'any': {
    name: 'any',
    description: 'Generated by SSO CLI',
    icon: '🆕',
    primaryColor: '#16A34A',
    redirectUrl: 'http://localhost:5173/callback'
  },
  'five': {
    name: 'five',
    description: 'Generated by SSO CLI',
    icon: '🆕',
    primaryColor: '#16A34A',
    redirectUrl: 'http://localhost:5173/callback'
  },
  'four': {
    name: 'four',
    description: 'Generated by SSO CLI',
    icon: '🆕',
    primaryColor: '#16A34A',
    redirectUrl: 'http://localhost:5173/callback'
  },
  'three': {
    name: 'three',
    description: 'Generated by SSO CLI',
    icon: '🆕',
    primaryColor: '#16A34A',
    redirectUrl: 'http://localhost:5173/callback'
  },
  'two': {
    name: 'two',
    description: 'Generated by SSO CLI',
    icon: '🆕',
    primaryColor: '#16A34A',
    redirectUrl: 'http://localhost:5173/callback'
  },
  'one': {
    name: 'one',
    description: 'Generated by SSO CLI',
    icon: '🆕',
    primaryColor: '#16A34A',
    redirectUrl: 'http://localhost:5173/callback'
  },
  'comet9': {
    name: 'comet9',
    description: 'Generated by SSO CLI',
    icon: '🆕',
    primaryColor: '#16A34A',
    redirectUrl: 'http://localhost:5173/callback'
  },
  'comet8': {
    name: 'comet8',
    description: 'Generated by SSO CLI',
    icon: '🆕',
    primaryColor: '#16A34A',
    redirectUrl: 'http://localhost:5173/callback'
  },
  '7890': {
    name: '7890',
    description: 'Generated by SSO CLI',
    icon: '🆕',
    primaryColor: '#16A34A',
    redirectUrl: 'http://localhost:5173/callback'
  },
  'comet6': {
    name: 'comet6',
    description: 'Generated by SSO CLI',
    icon: '🆕',
    primaryColor: '#16A34A',
    redirectUrl: 'http://localhost:5173/callback'
  },
  'comet5': {
    name: 'comet5',
    description: 'Generated by SSO CLI',
    icon: '🆕',
    primaryColor: '#16A34A',
    redirectUrl: 'http://localhost:5173/callback'
  },
  'spiddy': {
    name: 'spiddy',
    description: 'Generated by SSO CLI',
    icon: '🆕',
    primaryColor: '#16A34A',
    redirectUrl: 'http://localhost:5173/callback'
  },
  'spi': {
    name: 'spi',
    description: 'Generated by SSO CLI',
    icon: '🆕',
    primaryColor: '#16A34A',
    redirectUrl: 'http://localhost:5173/callback'
  },
  'checcc': {
    name: 'checcc',
    description: 'Generated by SSO CLI',
    icon: '🆕',
    primaryColor: '#16A34A',
    redirectUrl: 'http://localhost:5173/callback'
  },
  'ddd': {
    name: 'ddd',
    description: 'Generated by SSO CLI',
    icon: '🆕',
    primaryColor: '#16A34A',
    redirectUrl: 'http://localhost:5173/callback'
  },
  'new': {
    name: 'new',
    description: 'Generated by SSO CLI',
    icon: '🆕',
    primaryColor: '#16A34A',
    redirectUrl: 'http://localhost:5173/callback'
  },
  'hero': {
    name: 'hero',
    description: 'Generated by SSO CLI',
    icon: '🆕',
    primaryColor: '#16A34A',
    redirectUrl: 'http://localhost:5173/callback'
  },
  'demoday2': {
    name: 'demoday2',
    description: 'Generated by SSO CLI',
    icon: '🆕',
    primaryColor: '#16A34A',
    redirectUrl: 'http://localhost:5173/callback'
  },
  'demoday1': {
    name: 'demoday1',
    description: 'Generated by SSO CLI',
    icon: '🆕',
    primaryColor: '#16A34A',
    redirectUrl: 'http://localhost:5173/callback'
  },
  'demoday': {
    name: 'demoday',
    description: 'Generated by SSO CLI',
    icon: '🆕',
    primaryColor: '#16A34A',
    redirectUrl: 'http://localhost:5173/callback'
  },
  'demo6': {
    name: 'demo6',
    description: 'Generated by SSO CLI',
    icon: '🆕',
    primaryColor: '#16A34A',
    redirectUrl: 'http://localhost:5173/callback'
  },
  'demo5': {
    name: 'demo5',
    description: 'Generated by SSO CLI',
    icon: '🆕',
    primaryColor: '#16A34A',
    redirectUrl: 'http://localhost:5173/callback'
  },
  'demo4': {
    name: 'demo4',
    description: 'Generated by SSO CLI',
    icon: '🆕',
    primaryColor: '#16A34A',
    redirectUrl: 'http://localhost:5173/callback'
  },
  'demo3': {
    name: 'demo3',
    description: 'Generated by SSO CLI',
    icon: '🆕',
    primaryColor: '#16A34A',
    redirectUrl: 'http://localhost:5173/callback'
  },
  'deno2': {
    name: 'deno2',
    description: 'Generated by SSO CLI',
    icon: '🆕',
    primaryColor: '#16A34A',
    redirectUrl: 'http://localhost:5173/callback'
  },
  'demo1': {
    name: 'demo1',
    description: 'Generated by SSO CLI',
    icon: '🆕',
    primaryColor: '#16A34A',
    redirectUrl: 'http://localhost:5173/callback'
  },
  'che': {
    name: 'che',
    description: 'Generated by SSO CLI',
    icon: '🆕',
    primaryColor: '#16A34A',
    redirectUrl: 'http://localhost:5173/callback'
  },
  'check': {
    name: 'check',
    description: 'Generated by SSO CLI',
    icon: '🆕',
    primaryColor: '#16A34A',
    redirectUrl: 'http://localhost:5173/callback'
  },
  'board': {
    name: 'board',
    description: 'Generated by SSO CLI',
    icon: '🆕',
    primaryColor: '#16A34A',
    redirectUrl: 'http://localhost:5173/callback'
  },
  'today': {
    name: 'today',
    description: 'Generated by SSO CLI',
    icon: '🆕',
    primaryColor: '#16A34A',
    redirectUrl: 'http://localhost:5173/callback'
  },
  'temp2': {
    name: 'temp2',
    description: 'Generated by SSO CLI',
    icon: '🆕',
    primaryColor: '#16A34A',
    redirectUrl: 'http://localhost:5173/callback'
  },
  'hnm': {
    name: 'hnm',
    description: 'Generated by SSO CLI',
    icon: '🆕',
    primaryColor: '#16A34A',
    redirectUrl: 'http://localhost:5176/callback'
  },
  'hello': {
    name: 'hello',
    description: 'Generated by SSO CLI',
    icon: '🆕',
    primaryColor: '#16A34A',
    redirectUrl: 'http://localhost:5175/callback'
  },
  pms: {
    name: 'Property Management System',
    description: 'Manage your properties and tenants',
    icon: '🏢',
    primaryColor: '#10B981',
    redirectUrl: 'http://localhost:3001/callback'
  },
  analytics: {
    name: 'Analytics Dashboard',
    description: 'View reports and metrics',
    icon: '📊',
    primaryColor: '#8B5CF6',
    redirectUrl: 'http://localhost:3002/callback'
  },
  crm: {
    name: 'CRM',
    description: 'Customer relationship management',
    icon: '🤝',
    primaryColor: '#F59E0B',
    redirectUrl: 'http://localhost:3003/callback'
  },
  'admin-ui': { // ✅ ADD THIS
    name: 'Admin Dashboard',
    description: 'Manage users, clients, and system settings',
    icon: '⚙️',
    primaryColor: '#DC2626', // Red for admin
    redirectUrl: 'https://admin.local.test:5173/callback'
  },
  'account-ui': {
    name: 'Account Management',
    description: 'Manage your profile and settings',
    icon: '👤',
    primaryColor: '#3B82F6',
    redirectUrl: import.meta.env.VITE_REDIRECT_URI
  }
};

export function getClientConfig(id) {
  return CLIENT_CONFIGS[id] || CLIENT_CONFIGS['account-ui'];
}
